# Generated by Django 3.2.9 on 2022-03-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pers_acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='user',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
